# Generated by Django 5.2.1 on 2025-05-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
