# Generated by Django 5.2.1 on 2025-05-21 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='guard',
            name='guardImage',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
