# Generated by Django 5.2.1 on 2025-05-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0005_guard_guardimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='serviceIcon',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
