# Generated by Django 5.2.1 on 2025-06-03 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guard', '0006_service_serviceicon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
    ]
